version: '3'

services:

  tutum-helloworld:
    image: tutum/hello-world
    # ports:
    #   - 50080:80
    networks:
      - proxy
    labels:
      # - "traefik.backend=foo"
      - "traefik.port=80"
      - "traefik.protocol=https"
      - "traefik.weight=10"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:cftest.louislabs.com"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.priority=10"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.docker.network=proxy"

    container_name: tutum-helloworld
    restart: always

networks:
  proxy:
    external: true
